### ISSUE TITLE
请问如何解决这个问题

### ISSUE THREAD

**Issue by Santacruuuz** [bryant-video/neovim-tutorial#3]
[mason-lspconfig.nvim] Server "sumneko_lua" is not a valid entry in ensure_installed. Make sure to only provide lspconfig server names.
[mason-lspconfig.nvim] installing rust_analyzer
sumneko_lua is deprecated, use lua_ls instead. See :h deprecated
This function will be removed in lspconfig version 0.2.0
stack traceback:
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:36: in function '__index'
        ...y1er28/.config/nvim/lua/bryant/plugins/lsp/lspconfig.lua:129: in main chunk
        [C]: in function 'require'
        /home/y1er28/.config/nvim/init.lua:11: in main chunk

**Comment by iaso2h** [comment]
参考 [sumneko_lua is deprecated, use lua_ls instead](https://github.com/nvim-lua/kickstart.nvim/issues/171)
